#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>c"
echo "</title></head><body>"
echo ""
echo "<center>Information generated on $(date)</center>"
echo "</body></html>"

#/home/pi/geiger-work.sh
echo "$(/usr/bin/gnuplot /home/pi/gnuplot-geiger)"
echo "$(/usr/bin/gnuplot /home/pi/gnuplot-geiger-all)"
echo "$(tail -1440 /home/pi/accel.dat >/home/pi/accel24.dat)"
echo "$(tail -120 /home/pi/accel.dat >/home/pi/accel2h.dat)"
echo "$(/usr/bin/gnuplot /home/pi/gnuplot-geiger24)"
echo "$(/usr/bin/gnuplot /home/pi/gnuplot-geiger2h)"

#echo "$(cp /home/pi/a.png /usr/lib/cgi-bin/.)"
#echo "$(cp /home/pi/a24.png /usr/lib/cgi-bin/.)"
#echo "$(cp /home/pi/a2h.png /usr/lib/cgi-bin/.)"

echo "<img src=\"a.png\">"
echo "<img src=\"a-all.png\">"
echo "<img src=\"a24.png\">"
echo "<img src=\"a2h.png\">"

echo "<b><pre>Top 10</pre></b>"
echo "<pre> $(cat /home/pi/accel.dat | sort -n | tail -10)</pre>"
echo "<hr>"
echo "<b><pre>Bot 10</pre></b>"
echo "<hr>"
echo "<pre> $(cat /home/pi/accel.dat | sort -n | head -10)</pre>"
echo "<textarea rows="40" cols="50">"
echo "$(tail -1000 /home/pi/accel.dat)"
echo "</textarea>"

echo "<h1>Memory Info</h1>"
echo "<pre> $(free -m) </pre>"
echo "<h1>Disk Info:</h1>"
echo "<pre> $(df -h) </pre>"
echo "<h1>Logged in user</h1>"
echo "<pre> $(w) </pre>"
echo "<h1>Top CPU usage</h1>"
echo "<pre> $(ps aux --sort -rss | head -10)</pre>"
echo "<center>Information generated on $(date)</center>"
